[server]
    service_name="go-login"
    port = 10006
    app = "app"

[log]
    level="info"
    logpath="logs"
    rotate="hour"
    business_log_off=true
    succ_stat_code=[499,1601001,1601002,1062,1601003,1605001]

[[database]]
    name="go-login"
    master="root:123456@tcp(localhost:3306)/go-login?collation=utf8mb4_general_ci&loc=Asia%2FShanghai&parseTime=true&timeout=10s&readTimeout=5s&writeTimeout=5s"
    slaves=["root:123456@tcp(localhost:3306)/go-login?collation=utf8mb4_general_ci&loc=Asia%2FShanghai&parseTime=true&timeout=10s&readTimeout=5s&writeTimeout=5s"]

[[redis]]
    server_name="login"
    addr="localhost:6379"
    password=""
    max_idle=100
    max_active=100
    idle_timeout=5000
    connect_timeout=300
    read_timeout=200
    write_timeout=200
    slow_time=200
    retry=1
    database=0

[[redis]]
    server_name="login-code"
    addr="localhost:6379"
    password=""
    max_idle=100
    max_active=100
    idle_timeout=5000
    connect_timeout=300
    read_timeout=200
    write_timeout=200
    slow_time=200
    retry=1
    database=1

[[server_client]]
    service_name="social.strategy.tag"
    proto="http"
    endpoints_from="consul"
    balancetype="roundrobin"
    read_timeout=1000
    retry_times=1
    slow_time = 200

[[server_client]]
	service_name="social.profile.base"
	proto="http"
	endpoints_from="consul"
	balancetype="roundrobin"
	read_timeout=500
	retry_times=0
    slow_time =200
